### ISSUE TITLE
%language%.txt

### ISSUE THREAD

**Issue by NachoMuesa** [DrAbcOfficial/ABCEnchance#47]
They told me that the solution to this problem was to copy english.txt and rename it to %language%, but the problem has not been resolved. 

I attach screenshots so you can see.

![image](https://github.com/DrAbcOfficial/ABCEnchance/assets/154471547/b3ce85b7-3df3-4c57-8bc0-d49e07eb40a5)

![image](https://github.com/DrAbcOfficial/ABCEnchance/assets/154471547/baf01b81-8753-4f5b-a0e0-9f8661b697af)

**Comment by DrAbcOfficial** [comment]
It seems that your system language is not English or Chinese
If you are using a non-English or Chinese system, you can add `-forcelang english` to the Start Command Argument to force an English translation.
Or copy english.txt and rename it to spanish.txt
I personally prefer the second solution, because you can modify this txt to get the Spanish translation.

**Comment by NachoMuesa** [comment]
Thank you!
